version: "3"
services:

    chat:
        image: weslleycsil/chat-go:1.0.1
        networks:
            - traefik_proxy
            - backend
        depends_on:
            - hub
        deploy:
          replicas: 2
          labels:
            - "traefik.web.port=8000"
            - "traefik.docker.network=traefik_proxy"
            - "traefik.web.frontend.rule=Host:chat-go.twcreativs.stream"
        working_dir: /app

    hub:
        image: weslleycsil/hub-go:1.0.0
        networks:
            - backend
        working_dir: /app

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    backend: